config/routes.rb
WPrixes::Application.routes.draw do
  devise_for :users

  root to: 'home#show'

  resources :categories, only: [:index, :show] do
    resources :nominees, only: [:create]
  end
  resources :votes, only: [:create, :destroy]
  resources :results, only: [:index]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :nominees
  mount_uploader :image, PictureUploader

end

app/models/concerns/voter.rb
module Voter
  extend ActiveSupport::Concern

  included do

    def voted?(category)
      find_vote(category).present?
    end

    def find_vote(category)
      UserVoteCategoryQuery.new(self, category).get
    end

  end

end

app/models/nominee.rb
class Nominee < ActiveRecord::Base

  belongs_to :category
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  include Voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :init
  mount_uploader :avatar, PictureUploader

  def password_required?
    false
  end

  def init
    return if encrypted_password.present?
    pass = Digest::SHA1.hexdigest(email + Time.current.to_s)
    self.password = pass
    self.password_confirmation = pass
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :category
  belongs_to :user
  belongs_to :nominee

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_user
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :check_user

  def index
    categories = Category.all.sort
    @categories_voted = categories.reject { |c| current_user.voted? c }.shuffle
    @categories_not_voted = categories.select { |c| current_user.voted? c }
  end

  def show
    @category = Category.find(params[:id])
    @not_nominated_users = UsersNotNominatedQuery.new(@category).get.order(name: :asc)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
    return redirect_to new_user_session_path unless user_signed_in?
    redirect_to categories_path
  end

end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController

  before_filter :check_user

  def create
    category = Category.find(params[:category_id])
    Nominee.create!(resource_params.first) unless category.is_closed_to_nominate
    redirect_to :back 
  end

  def resource_params
    return [] if request.get?
     [params.require(:nominee).permit(:category_id, :user_id)]
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  before_filter :check_user

  def index
    redirect_to :back unless current_user.is_admin
    @results = ResultsContext.new.get
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :check_user

  def create
    return redirect_to :back if current_user.voted?(Category.find(resource_params.first[:category_id]))
    @vote = Vote.create!(resource_params.first)
  end

  def destroy
    vote = Vote.find(params[:id])
    if current_user.id == vote.user.id
      vote.destroy!
    end
    redirect_to :back
  end

  private

  def resource_params
    return [] if request.get?
     [params.require(:vote).permit(:category_id, :user_id, :nominee_id)]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_table_category.html.slim
a href=category_path(category)
  - color = voted ? '' : 'success'
  = image_tag category.image, class: 'avatar'
  a.button.m10 href=category_path(category) class=color
    h4.white = category.title
br

app/views/categories/index.html.slim
h1 Bienvenido a los W-awards 2014
h3 Categorias
div
  - @categories_voted.each do |c|
    = render 'table_category', category: c, voted: false
  - @categories_not_voted.each do |c|
    = render 'table_category', category: c, voted: true
br
- if current_user.is_admin
  a.button.alert href=results_path Resultados

app/views/categories/show.html.slim
h2 = @category.title
h4 = @category.description
- if current_user.voted?(@category)
  p = "Ya votaste a #{current_user.find_vote(@category).nominee.user.name} capo"
  = form_tag vote_path(current_user.find_vote(@category).id), method: :delete
    input type='submit' class='button alert' value='Borrar mi voto'
- else
  h5 Vota a un nominado!
  div
    - @category.nominees.each do |n|
      = form_for Vote.new, url: votes_path, class: 'new_vote' do |f|
        = image_tag n.user.avatar, class: 'avatar'
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :category_id, value: @category.id
        = f.hidden_field :nominee_id, value: n.id
        = f.submit n.user.name, class: 'button'
  - unless @category.is_closed_to_nominate
    br
    h5 O nomina a alguien mas!
    = form_for Nominee.new, url: category_nominees_path(@category) do |f|
      .row
        .columns.small-4
          = f.select :user_id, options_for_select: @not_nominated_users.map { |u| [u.name, u.id] }
          = f.hidden_field :category_id, value: @category.id
          = f.submit 'Agregar', class: 'button alert'
a.button.success href=categories_path Volver

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WPrixes
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/application.html.slim
html
  head
    title WPrixes
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css" /
  body
    .row.mainRow
      p.notice = notice
      p.alert = alert 
      = yield

app/views/results/index.html.slim
- @results.each do |r|
  - unless r[:results].nil?
    - keys = r[:ordered_results].map { |a| a[0].name }
    - results = r[:ordered_results].map { |a, b| [a.name, b] }
    .chart id=r[:category] data-results=results data-keys=keys
      h3.title = r[:category]
      .row
        .columns.small-4
          p = "1. #{r[:ordered_results][0][0].name} con #{r[:ordered_results][0][1]} votos"
          = image_tag r[:ordered_results][0][0].avatar, class: 'avatar'
        .columns.small-4
          - if r[:ordered_results].length >= 2 
            p = "2. #{r[:ordered_results][1][0].name} con #{r[:ordered_results][1][1]} votos"
            = image_tag r[:ordered_results][1][0].avatar, class: 'avatar'
        .columns.small-4
          - if r[:ordered_results].length >= 3
            p = "3. #{r[:ordered_results][2][0].name} con #{r[:ordered_results][2][1]} votos" 
            = image_tag r[:ordered_results][2][0].avatar, class: 'avatar'
      br
      .chart-container
      hr
a.button.success href=categories_path Volver

app/views/votes/create.html.slim
h3 = "Votaste a #{@vote.nominee.user.name} para la categoria #{@vote.category.title}"
a.button.success href=categories_path Volver